version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: example/server:latest
    ports:
      - "8761:8761"

  comm-client:
    build:
      context: ./comm-client
      dockerfile: Dockerfile
    image: example/comm-client:latest
    ports:
      - "8081:8081"

  profile-service:
    build:
      context: ./profile-service
      dockerfile: Dockerfile
    image: example/profile-service:latest
    ports:
      - "8082:8082"

